<?php if(!defined('FastCore')){exit('Opss!');}
# Заголовки
$opt = array(
'title' => 'Day June hamster_kombat bot',
'keywords' => 'скрипт, хайпы, игры, бонусы, серфинги, php7, apache, nginx',
'description' => 'Hamster combo day June economic game play hamster_kombat bot'
);

?>

<div class="center-title mt-2">
<h2>Terms & Conditions</h2>
</div>
<div class="p-1">


<div class=""><p>Updated June 10, 2024.</p>
<p>THESE TERMS OF SERVICE AND CONDITIONS APPLY TO THE USE OF THE <?=$config->sitename;?> WEBSITE LOCATED AT <?=$config->sitename;?>.</p>
<p><b>HOW TO ACCEPT THIS AGREEMENT</b></p><p>You accept this Agreement by:</p>
<p>Written consent through accepting this Agreement on the website, via e-mail or otherwise by executing this Agreement or activating the Services.</p>
<p>When you accept this Agreement, you specify that you are at least 18 years old and are legally able to enter into a contract. If you accept this Agreement on behalf of the organization, you specify that you are an authorized representative of such organization, and where the context requires, “you” means the “organization”. By accepting, you agree to every provision of this Agreement whether you have to read it or not.</p><p>Once you have accepted this Agreement, we will process your acceptance as an offer to receive Service. We will then review the offer, including without limitation assessing your identity and authenticity. Once we are ready to offer Service for you, we will inform you that your Service has commenced, constituting our acceptance of your offer.</p><p>If we feel unable, or if at our sole discretion, we decide not to provide the Service to you, we will inform you on the matter by email and we will not process your order. If you have already paid for the Services, we will refund you the full amount as soon as possible in the same method of payment used in the attempted purchase of Services.</p><p>Our Agreement</p><p>This Agreement establishes the legal terms and conditions of the agreement between us (collectively referred to as the “Agreement”) under which we sell any of the Services to you (defined below) that are described on our website (hereinafter referred to as the “Site”).</p><p>For purposes of this Agreement, “you” or “your” refer to the customer agreeing to the terms and conditions of this Agreement; “us”, “we”, or “our” refer to TRONMIENR .</p><p>This Agreement is applicable to any Services (defined below). Please read this Agreement carefully and make sure that you understand it before ordering any Services from the Site. Please note that by purchasing a Service, you agree to be bound by this Agreement and the other documents expressly referred herein.</p><p>You should print a copy of this Agreement or save it for your future reference.</p><p>Every time you purchase a Service, please refer to the latest version of this Agreement made available on the Site to ensure you understand the current terms and conditions. This Agreement was most recently updated on updated December 10, 2023.</p><p>This Agreement is only in the English language.</p><ol><li>INFORMATION ABOUT US</li>
<dl><dt><b>1.1.</b> We operate the Site <a href="/" rel="nofollow"><?=$config->sitename;?></a>. To contact us, please see our <b>customer support</b> page.</dt></dl>
<li>OUR SERVICES</li>
<dl><dt><b>2.2.</b> <u>Mining Contracts</u>.</dt><br><dd><b>a.</b> When you enter this Agreement empowering us to provide you the Service, and we accept your request by sending you an notification in your Dashboard; a contract (hereinafter referred to as “the Plan”) to provide the Service is formed. Upon commencement of Service, we will allocate a part of Mining Hardware equal to a certain amount of the Litecoin mining computer computational power to you to carry out mining of Litecoin.</dd>
<dd><b>b.</b> The types of Plans potentially available at any time are described in detail at. You must have purchased a Plan to have any right to use Services to obtain any right to Product.</dd><br>
<dt><b>2.6.</b> <u>Service Fee &amp; Maintenance fees</u>. All miners are free to mine and maintain for the duration of the plan. After the plan expires it will be reset to the Free plan and start charging fee (fixed fee 10 TRX). Free plan is free all fee for one year.</dt><br></dl>
<li>YOUR ACCOUNT</li>
<dl><dt><b>3.1.</b> <u>Password</u>. As part of the process of selecting and paying for the Services, you are required to create an account on the Site (hereinafter referred to as “the Account”) and to provide your Litecoin wallet address (hereinafter referred to as “the Litecoin wallet”) and password (hereinafter referred to as “the secure PIN”). To protect your Account and to prevent unauthorized access to it, keep your secure PIN confidential. You are responsible for any activity that occurs on or through your Account. If you become aware of or suspect any unauthorized use of your Password or Account, please contact Trxminer Support Team to change your PIN immediately and notify us as soon as possible. If we believe that there has been unauthorized access to your Account, we reserve the unilateral right to suspend or discontinue any and all Services, your Account, and in such a case we will endeavor to notify you.</dt><br>
<dt><b>3.2.</b> <u>Litecoin Wallet</u>. Your Litecoin Wallet” is the Litecoin wallet address that you provide to us from time to time for the payment to you. We do not operate your Litecoin Wallet. By entering Litecoin Wallet address you acknowledge the ownership of it. You are solely responsible for maintaining and controlling your Litecoin Wallet. Be sure to safeguard the access credentials to your Litecoin Wallet. Any Product is only as secure as your confidential access credentials. If you forget or misplace your access credentials to your Litecoin Wallet or if others gain access to your Litecoin Wallet, with or without your authorization, you could permanently lose your Litecoin assets, including any litecoins we transfer to your Litecoin Wallet. To be clear, we have no liability for any operation or failure of your Litecoin Wallet.</dt><br></dl>
<li>USE OF THE SITE</li>
<dl><dt>Your use of the Site is governed by this Agreement as posted on the Site from time to time. Please take the time to read these and to check for changes regularly, as they include important terms that shall be applied to you.</dt><br></dl>
<li>USE OF OUR SERVICES</li>
<dl><dt><u>Access Requirements</u>. Before you can use our Services, you must have a valid Service, we must approve such Service, and you must have a valid Account include email address. <br></dt><br></dl>
<li>PRICE OF SERVICES</li><dl><dt><b>6.1.</b> <u>Prices</u>. Price for Services will be as quoted on the Site from time to time. We take all reasonable care to ensure that the prices of the Services are correct at the time when the relevant information is entered into the system. However, if we discover an error in the price of a Service you ordered, your order will be revised.</dt><br>
<dt><b>6.2.</b> <u>Change in Prices</u>. Prices for our Services may change from time to time.</dt><br><dt><b>6.3.</b> <u>VAT</u>.The price you paid to buy a plan is the final price you pay. You will not be charged any additional VAT charges.</dt><br></dl>
<li>RESTRICTIONS ON USE</li><dl><dt><u>Our Remedies</u>. If we have reason to believe that you or any entity under your common ownership or control have engaged in any of the prohibited or unauthorized activities described in this Agreement, have otherwise breached your obligations under this Agreement, have misappropriated our trade secrets or our Confidential Information, copyrights, patents or other intellectual property rights, then without demand or prior notice and without limiting any of its other available remedies, we may:</dt><br>
<dd><b>a.</b> terminate, suspend or limit your access to or use of your Account or our Services;</dd>
<dd><b>b.</b> terminate or suspend this Agreement or any Service;</dd>
<dd><b>e.</b> refuse to provide our Services to you in the future;</dd></dl>
<li>TECHNOLOGY</li><dl><dt><b>8.1.</b> <u>Definition</u>. “Technology” means our or our Suppliers' computer programs, literary works, audiovisual works, all other original works of expression, methods, apparati and processes that we publish, distribute, use or otherwise exploit to facilitate your use of our Services, and includes without limitation our Software, software tools, user interface designs, and any derivatives, improvements, enhancements or extensions thereof developed or provided by us or our Suppliers and used in the provision of our Services.</dt><br>
<dt><b>8.2.</b> <u>Ownership</u>. This Agreement does not transfer to you any ownership or proprietary rights in the Technology or any work or any part thereof, and all right, title and interest in and to the Technology will remain solely with us or our Suppliers. You are not purchasing title to any Technology. If you are approved to use our Services, you are permitted to use Technology only as enabled and attended through your Account at the Site and only during the Term. That permission is for the sole purpose of enabling you to use our Services in the manner permitted by this Agreement. Your rights under this Agreement shall not be transferred to any other person without our prior express written consent.</dt><br>
<dt><b>8.3.</b> <u>Restrictions on Use</u>. You will not copy Technology or use Technology independently other than as set forth above, and we grant you no license, whether express or implied, in any copyright, patent or any other intellectual property rights embodied in Technology.</dt><br></dl>
  <li>HOW WE USE YOUR PERSONAL INFORMATION</li>
  <dl><dt>We only use the information you provide to notify account-related issues and website-related content. In addition we do not use your information for any other purpose. 
All your personal information is protected.</dt><br></dl>
<li><b>OUR LIABILITY TO YOU IS LIMITED TO THE SERVICE FEE</b></li>
<dl><dt><b>10.1.</b> <u>Exclusions</u>. Nothing in this Agreement limits or excludes our liability for:</dt><br>
<dd><b>a.</b> death or personal injury caused by our negligence; or</dd>
<dd><b>b.</b> fraud or fraudulent misrepresentation.</dd><br>
<dt><b>10.2.</b> <u>THE COMPANY'S SUPPLIERS</u></dt><br>
<dd>We use the Site to resell the hashing power provided by our Suppliers. For the avoidance of doubt, the Suppliers retain the responsibility to the final users of the hashing power for providing the Services.</dd></dl>
<li>OTHER IMPORTANT TERMS</li>
<dl><dt><b>11.2.</b> <u>Entire Agreement</u>. This Agreement (including any Services) constitutes the entire agreement between you and us. You acknowledge that you have not relied on any statement, promise or representation made or given by or on behalf of us which is not set out in this Agreement.</dt><br><dt><b>11.3.</b> <u>Our Assignment</u>. We may transfer or assign our rights and obligations under this Agreement or a Service to another entity, but this will not affect your rights or our obligations under this Agreement or the terms of the Service. We will endeavor to notify you in writing if this happens.</dt><br><dt><b>11.4.</b> <u>Your Assignment.</u> A Service is between you and us, and you may not assign, transfer, sublease, encumber or subject to any security interest a Service without written authorization from us. Any attempted assignment in violation of this Agreement will be void and of no effect.</dt><br><dt><b>11.5.</b> <u>Third Party Beneficiaries</u>. No other person, except you, shall have any rights to enforce this Agreement or a Service, whether under the Contracts or otherwise.</dt><br><dt><b>11.6.</b> <u>Severability</u>. If any provision of this Agreement is held to be invalid or unenforceable, including without limitation anything regarding the arbitration process, such provision will be struck from this Agreement only to the extent it is invalid or unenforceable. Unless otherwise provided, all other terms of this Agreement will remain in full force and effect.</dt><br><dt><b>11.7.</b> <u>Waiver</u>. If we fail to insist that you perform any of your obligations under this Agreement, or if we do not enforce our rights against you, or if we delay in doing so, that will not mean that we have waived our rights against you and will not mean that you do not have to comply with those obligations. If we do waive a default by you, we will only do so in writing, and that will not mean that we will automatically waive any later default by you.</dt><br><dt><b>11.8.</b> <u>Conflict</u>. If there is a conflict between this Agreement and something stated by any Other Entity, whether before or after you enter into this Agreement, the terms of this Agreement will prevail.</dt><br>
<dt><b>11.9.</b> <u>Survival</u>. Any terms of this Agreement which by their nature should survive will survive the termination of this Agreement.</dt><br></dl></ol></div>
</div>
